[package]
name = "typed-session-axum"
version = "0.1.0-alpha.0"
description = "Cookie-based sessions for Axum via typed-session"
edition = "2021"
homepage = "https://github.com/ISibboI/typed-session-axum"
license = "MIT OR Apache-2.0"
keywords = ["axum", "session", "sessions", "cookie", "typed-session"]
categories = ["web-programming"]
repository = "https://github.com/ISibboI/typed-session-axum"
documentation = "https://docs.rs/typed-session-axum"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typed-session = "0.1.0-alpha.0"
http-body = "0.4.5"
tracing = "0.1"
async-trait = "0.1.59"
axum = {version = "0.6.1", features = ["headers"]}